# Generated by Django 3.1.6 on 2021-02-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210222_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='Listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='auction',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='auction',
            new_name='listing',
        ),
    ]
