# Generated by Django 3.1.6 on 2021-02-22 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210222_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
