# Generated by Django 3.1.6 on 2021-02-22 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210222_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
